### ISSUE TITLE
Existing CSS IDs break functionality

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/permalink_filter#5]
I've found that pasting text from Google Docs breaks the functionality. The headings all have a Google Docs id when pasted, and unless I manually remove that, the permalinks don't actually work.

For reference, here's an example of what Google Docs produces:

```
<h3 dir="ltr" id="docs-internal-guid-3d821b3e-7fff-f702-123c-3483af00ce2e"><strong>Headline</strong></h3>
```

The module produces a link based on the headline, but it doesn't match the ID that Google has produced.

**Comment by ghost** [comment]
Thanks @laryn, I can confirm this bug.

It seems to be a problem with my regular expression for pulling out IDs (no surprise there, since I'm no kind of regex expert). I was going to post a question about this to [StackOverflow](https://stackoverflow.com/questions/tagged/regex), when I read this:

> NOTE: Asking for HTML, JSON, etc. regexes tends to be met with negative reactions. If there is a parser for it, use that instead.

So I guess I should use something else instead (like PHP DOM). Looking into that now...

**Comment by ghost** [comment]
@laryn Here's a PR: https://github.com/backdrop-contrib/permalink_filter/pull/6 Please test and let me know how that goes for you.

**Comment by laryn** [comment]
@BWPanda Yes, have had a chance to test and this seems to solve it!

**Comment by ghost** [comment]
Awesome, merged!
